## Foundational model

We start by trying to adequately controlling for the following two types of factor:

- Demographic factors, such as age and sex
- Event history: i.e. the current observed economic (in)activity status that persons are observed to occupy at a given time point

## Extended models

An extended model adds one or more variables to the foundational model. These additional variables are the factors/determinants whose effect on economic (in)activity we are actually interested in estimating for both individuals and populations.

### Health as a discrete and continuous variables

The health extended model adds the variables:

- **Discrete**: `health`: Do you have any long-standing physical or mental impairment, illness or disability? By 'long-standing' I mean anything that has troubled you over a period of at least 12 months or that is likely to trouble you over a period of at least 12 months. 
- **Continuous**: `sf12mcs_dv` (SF-12 Mental Component Summary (MCS)) and `sf12pcs_dv` SF-12 Physical Component Summary (PCS). We standardise both scores. The version chosen was one both mental and physical health scores are included as an interactive term, where physical health contributed twice as strongly as mental health.


